CREATE TABLE AirQuality (
    stationName VARCHAR(30) NOT NULL,
    stationCode VARCHAR(6) NOT NULL,
    mangName VARCHAR(10) NOT NULL,
    sidoName VARCHAR(10) NOT NULL,
    dataTime DATETIME NOT NULL,
    so2Value DECIMAL(8,6) NULL,
    coValue DECIMAL(5,4) NULL,
    o3Value DECIMAL(6,5) NULL,
    no2Value DECIMAL(6,5) NULL,
    pm10Value INT NULL,
    pm10Value24 INT NULL,
    pm25Value INT NULL,
    pm25Value24 INT NULL,
    khaiValue INT NULL,
    khaiGrade INT NULL,
    so2Grade INT NULL,
    coGrade INT NULL,
    o3Grade INT NULL,
    no2Grade INT NULL,
    pm10Grade INT NULL,
    pm25Grade INT NULL,
    pm10Grade1h INT NULL,
    pm25Grade1h INT NULL,
    so2Flag VARCHAR(10) NULL,
    coFlag VARCHAR(10) NULL,
    o3Flag VARCHAR(10) NULL,
    no2Flag VARCHAR(10) NULL,
    pm10Flag VARCHAR(10) NULL,
    pm25Flag VARCHAR(10) NULL,
    api_update_date DATETIME NULL,
    PRIMARY KEY (stationCode, dataTime)
);
