CREATE TABLE device_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DeviceID VARCHAR(36) NOT NULL UNIQUE,
    PushToken VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
