// disasterCategories.js
const disasterCategories = [
    { label: "기타", value: "기타" },
    { label: "폭염", value: "폭염" },
    { label: "태풍", value: "태풍" },
    { label: "전염병", value: "전염병" },
    { label: "화재", value: "화재" },
    { label: "테러", value: "테러" },
    { label: "수도", value: "수도" },
    { label: "강풍", value: "강풍" },
    { label: "실종", value: "실종" },
    { label: "호우", value: "호우" },
    { label: "지진", value: "지진" },
    { label: "산사태", value: "산사태" },
    { label: "교통사고", value: "교통사고" },
    { label: "교통", value: "교통" },
    { label: "정전", value: "정전" },
    { label: "대설", value: "대설" },
    { label: "산불", value: "산불" },
    { label: "민방공", value: "민방공" },
    { label: "금융", value: "금융" },
    { label: "통신", value: "통신" },
    { label: "풍랑", value: "풍랑" },
    { label: "교통통제", value: "교통통제" },
    { label: "홍수", value: "홍수" },
    { label: "붕괴", value: "붕괴" },
    { label: "가뭄", value: "가뭄" },
    { label: "환경오염사고", value: "환경오염사고" },
    { label: "미세먼지", value: "미세먼지" },
    { label: "황사", value: "황사" },
    { label: "건조", value: "건조" },
    { label: "한파", value: "한파" },
    { label: "폭발", value: "폭발" },
    { label: "지진해일", value: "지진해일" },
    { label: "에너지", value: "에너지" },
  ];
  
  export default disasterCategories;
  